name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # test-and-lint:
  #   name: Lint & Test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.12"

  #     - name: Install dependencies
  #       run: |
  #         pip install -r requirements.txt
  #         pip install pytest ruff

  #     - name: Lint code
  #       run: ruff check .

      # - name: Run tests
      #   env:
      #     CI: true
      #   run: pytest

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    # needs: test-and-lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t fastapi-app .

  api-smoke-test:
    name: API Smoke Test
    runs-on: ubuntu-latest
    # needs: docker-build

    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t fastapi-app .

      - name: Run container
        run: |
          docker run -d -p 8000:8000 -e CI=true --name app fastapi-app

      - name: Wait for app to start
        run: sleep 150

      - name: Test API docs endpoint
        run: curl --fail http://localhost:8000/docs

      - name: Show logs if failed
        if: failure()
        run: docker logs app

  # security-check:
  #   name: Dependency Security Check
  #   runs-on: ubuntu-latest
  #   needs: test-and-lint

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.12"

  #     - name: Install pip-audit
  #       run: pip install pip-audit

  #     - name: Run security audit
  #       run: pip-audit

  # type-check:
  #   name: Type Checking
  #   runs-on: ubuntu-latest
  #   needs: test-and-lint

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.11"

  #     - name: Install mypy
  #       run: pip install mypy

  #     - name: Run type checks
  #       run: mypy .
  